# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d11e90dfa3b0d703c35d9e479495c4656bae43706f80cb3f5e125f82017af1dfc40674773311357747ec138ea92a433b984d807e42370073c29529b16a94835

test:
  secret_key_base: 2954d773a8a9e522441dbafd717e690e220df05b4dc1135ca98ca4332d43ba1eb66ca606516d7bed306c634040045d02b11990b2c649b28cc31d7c01890fffe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
